### ISSUE TITLE
Deploying stucks at "Installing Appx Package"

### ISSUE THREAD

**Issue by nobodykid** [ms-iot/vscode#14] opened 2016-09-25 14:02 UTC
I tried using the extension on my Visual Studio Code. But when I did "Run remote script", the deployment process took a very long time on "Installing Appx Package..."

I tried this by following the "Hello World" sample as instructed on the [Marketplace page](https://marketplace.visualstudio.com/items?itemName=ms-iot.windowsiot)

**Comment by paulmon** [comment] 2016-09-27 22:51
If you try executing 'run remote script' again does the same thing happen?

**Comment by nobodykid** [comment] 2016-09-28 15:32
Yes, it keeps stuck at that point

**Comment by paulmon** [comment] 2016-09-28 17:31
If you run the command "iot: Get Installed Packages" does one of the packages listed have a line with
"PackageFamilyName: NodeScriptHost" ?

**Comment by nobodykid** [comment] 2016-09-29 05:36
I'm afraid I don't have that name

**Comment by IoTGirl** [comment] 2017-01-24 23:07
Hi nobodykid,
It sounds like you may have something missing in your setup as you should have NodeScriptHost available.  Can you please follow the complete steps at WindowsOnDevices.com and try again?
I am closing this issue as we are not able to reproduce the issue with the steps provided. 
Sincerely,
IoTGirl

**Closed by IoTGirl** 2017-01-24 23:07 UTC
